{% set name = "flet-core" %}
{% set version = "0.14.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/flet_core-{{ version }}.tar.gz
  sha256: 838a30e5e21aadd4e9d1cdce1ec0f2627f9e27c97658e484a17ac95baa77cc2e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - poetry-core
    - python >=3.7.0,<4.0.0

  run:
    - python >=3.7.0,<4.0.0
    - typing-extensions >=4.6.2,<5.0.0
    - repath >=0.9.0,<0.10.0

test:
  imports:
    - flet_core
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/flet-dev/flet
  dev_url: https://github.com/flet-dev/flet/tree/main/sdk/python/packages/flet-core
  summary: Flet core library for Flet framwork sdk development.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
